version: '3'
services:
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8088:8088"
    env_file: ./.env
    environment:
      - DB_HOST= mongodb_server
      - DB_NAME= $MONGODB_DATABASE
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_PORT= $MONGODB_DOCKER_PORT
    depends_on:
      - mongodb
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports: 
      - "80:80"
    depends_on:
      - backend
  mongodb:
    image: mongo:latest
    container_name: mongodb_server
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - ./../mydata:/data/db
volumes:
  mydata:

